services:
  frontend:
    build: frontend/.
    ports:
      - "8080:8080"
    environment:
      - BACKEND_DNS=backend
      - BACKEND_PORT=9000
  backend:
    build: backend/.
    ports:
      - "9000:9000"
