name: Continuous Deployment
on:
  registry_package:
    types: [published, updated]

jobs:
  deploy:
    name: "Deploy Application"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ls -la
      - run: echo "${{ secrets.KUBECONFIG }}" | base64 -d > kubeconfig
      - run: kubectl --kubeconfig kubeconfig apply -f .deployments/
