name: "Package Application"
on:
  workflow_call:
    inputs:
      directory:
        description: "The directory of the application"
        type: string
        required: true
      docker_username:
        description: "Docker Hub username"
        type: string
        required: true
      docker_password:
        description: "Docker Hub password"
        type: string
        required: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.21"
      - run: |
          go version
          cd ${{ inputs.directory }}
          go test
          go build -o app
      - uses: actions/upload-artifact@v4
        with:
          name: app
          path: .
  image:
    runs-on: ubuntu-22.04
    needs: [build]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: app
          path: .
      - uses: docker/login-action@v3
        with:
          username: ${{ inputs.docker_username }}
          password: ${{ inputs.docker_password }}
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          push: true
