name: "Validate correct YAML in workflow files"
on:
  push:
    paths:
      - .github/workflows/**
  pull_request:
    paths:
      - .github/workflows/**

jobs:
  validate-yaml:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Validate each workflow file
        run: |
          shopt -s nullglob # fix for missing patterns
          for file in .github/workflows/*.yaml .github/workflows/*.yml; do
            echo "Validating $file"
            yq 'true' "$file" > /dev/null
          done
